### ISSUE TITLE
The location of file $config.dat

### ISSUE THREAD

**Issue by John5465** [aauc-mechlab/JOpenShowVar#10]
Hello! I wonder where the file $config.dat is located? Is the file in Kuka smartpad? I tried to find the correct $config.dat but failed. Can you tell me the location of file $config.dat? Thanks!

**Comment by markaren** [comment]
Login to the smartpad as a user with elevated rights (i.e. expert). $config.dat is located in R1/System.
Please refer to the manual or contact KUKA support for such questions in the future. Thanks.

**Comment by John5465** [comment]
Thank you!
