### ISSUE TITLE
 Software limit switch point cannot be reacher +A3

### ISSUE THREAD

**Issue by jianghancheng** [aauc-mechlab/JOpenShowVar#11]
Hello,  I want to send "MYPOS" request to move the KUKA robot and got " Software limit switch point cannot be reacher +A3" error. I saw that you wrote the solution "what I did was to copy the X, Y and Z values from MYPOS into a locally declared POS variable, which then has the default S and T values. Continuous movement did then work."
Sorry, I am a novice about KRL. Can you write several sample codes?

Thank you

**Comment by markaren** [comment]
Sorry, dont have time and have not worked with KRL in years. As this is an issue not really related to JOpenShowVar, but the KRL language in general. I would refer to KUKA support and the manual.
But the gist of the issue you describe is that a newly declared POS variable will have S and T values of 0. This is probably not what you want. Use the current S and T in-stead. This is all I can help you with.
