### ISSUE TITLE
Reg. connection between JOpenShowVar and KR C4 (Compact)

### ISSUE THREAD

**Issue by CaptainMack** [aauc-mechlab/JOpenShowVar#2]
Hi,

I'm using a KR C4 Compact (I guess it's the same for all C4 versions?) and I'm trying to connect JOpenShowVar to the robot using ApplicationLauncher.java. I've got the Proxy running on the Windows 7 Embedded on the KR C4 and added port 7000 tcp/udp on the SmartPad. I guess there's two questions to this. I've connected a ethernet cable to the EtherCat (X69) port and put it in a switch allowing my laptop retrieve an ip-address from the KR C4, which enables me to ping the Windows IP (192.168.0.1) and the SmartPad ip (172.31.1.147) from my laptop (172.17.255.1), I cannot, however, connect to the PROXY without it throwing a time-out. I've tried to enter a static IP like 192.168.0.5 or 172.31.1.150, but then I cannot ping any of the other ip addresses? 

Question 1:
Am i using the wrong ethernet port on the KR C4? There's both the KONI, X69, X66 etc.

Question 2: 
Am i doing something wrong when connecting, e.g. setting the wrong static ip? or is it because of the two filters on the SmartPad? EtherType filters?

**UPDATE:**
By letting my laptop recieve an ip address (172.17.255.129) from the KR C4 controller, it's possible to ping from the KR C4 controller (192.168.0.1) to my laptop (172.17.255.129). **However!**, I cannot ping from my laptop to the KR C4 controller - what am I missing?

All the best,
Chris

**Comment by markaren** [comment]
Hi, 

I will see if I can answer your question during the weekend. Been a while since I had my hands on the robot, so I don't have it in my head right now.

**Comment by CaptainMack** [comment]
Thank you @markaren, I'll be working on it for some time, so I'll update here if I find anything. I think the major problem is that I'm unsure if I'm connecting to the robot via. the right connector (x66, x69 and so forth). I've made some connections on the X11, so the KLI interface on X69 can't be used as far as I understand and the KLI ip is the standard 172.31.1.147. However! Let me illustrate the problem reg. pinging and connected via. X69 DHCP'ed IP:

192.168.0.1 (Win7Embedded) -> 172.31.1.147 (KLI) -> 172.17.255.129 (Win Laptop)

172.17.255.129 (Win Laptop) -> 172.31.1.147 (KLI), but can't reach 192.168.0.1 by pinging (However, I can ping 192.168.0.2, which is listed as the gateway to 192.168.0.1).

However, as stated in the readme: 
"In order to successfully establish an connection to the server. Your IP must be assigned a static IP in the same subrange as the one defined in the the SmartPads network configuration."

I can only ping from KR C4 to Laptop when using dynamic on the laptop (still using fixed ip on the KR C4), I know there's about three (?) networks internally that I've been in touch with:

**So the question is really If I'm connecting via. the right port on the C4 and if my network settings on the laptop is correctly or do I need the Ethernet KRL package for it to work?**

**Comment by CaptainMack** [comment]
I figured it out! Apparently there was conflicts somewhere, which I solved by making the C4 get the ip dynamically from my own router (i couldn't get static ip to work) No need to waste your weekend on this problem!
