### ISSUE TITLE
Java.lang.StringIndexOutOfBoundsException: String index out of range: -2

### ISSUE THREAD

**Issue by CaptainMack** [aauc-mechlab/JOpenShowVar#3]
Hi,

When running the text program against a physical KR C4 controller, I get the following error:

```
KRLVariable{id=1, name=MYPOS, value={T=0.0, A=0.0, S=0.0, B=0.0, C=0.0, Y=20.0, X=20.0, Z=0.0}, readTime=14ms}
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
    at java.lang.String.substring(String.java:1911)
    at no.hials.crosscom.KRL.structs.KRLStruct.setValueFromString(KRLStruct.java:67)
    at no.hials.crosscom.KRL.KRLVariable.update(KRLVariable.java:108)
    at no.hials.crosscom.CrossComClient.readVariable(CrossComClient.java:257)
    at no.hials.Test.main(Test.java:56)
```

It throws this error, when it gets to "client.readVariable(pos);" or some of the other readVariable functions.

I do not know if this is why, It doesn't move the robot manipulator (or if it's because I haven't set move_enabled in EXT-mode) as I've tried outcommenting these functions letting the program run.

**Comment by markaren** [comment]
Is there a "MYPOS" variable declared manually by you in the controller's cofig.dat?

**Comment by CaptainMack** [comment]
Thank you for your reply @markaren,

I'm unsure what type i should declare MYPOS under USER GLOBALS, since it should have XYZABC, but I'm not familiar with it.

Shouldn't it be:

MYPOS={X 0.0 Y 0.0 Z 0.0 A 0.0 B 0.0 C 0.0} ?

**Comment by markaren** [comment]
It's a POS struct. 

But reading/writing the already declared variables on the controller like OV_JOG works right?

**Comment by CaptainMack** [comment]
Yes, OV_PRO and OV_JOG works, so It's the way I declare the MYPOS variable that is not working. So I guess it should be POS MYPOS={X 0.0, Y 0.0, Z 0.0, A 0.0, B 0.0, C 0.0}, if I'm not mistaken

**Comment by markaren** [comment]
Yes, something like that. I also think that if you leave out some of the variables that would still work (only declaring x, y and z for instance is still valid, the rest is filled in under the hood).

**Comment by CaptainMack** [comment]
I was first unsure (when first asking this question about the string error) If I needed to create a custom program or If I could just handle it automatically through the EXT mode (using KUKAVARPROXY as sort of a PLC), I see now that I need to create a custom mode to react to the MYPOS variable, however, I am unable to use the following (saved as proxy.src)
 
    DEF ACTUATOR()
      INI
      PTP HOME Vel = 100 % DEFAULT
      $ADVANCE=1
      LOOP
      PTP_REL MYPOS C_PTP
      ENDLOOP
      PTP HOME Vel = 100 % DEFAULT
    END

As it creates a compilation error on the SmartPad (KSS01421), when trying to load it as a program.


I apologize for my lack of knowledge in this area, causing these low-level questions.

**Comment by CaptainMack** [comment]
I'm getting a:

```
Variable not declared
PTP_REL MYPOS C_PTP 
```

error, however two config.dat files exist, but I'm pretty confident that it's only the one containing a fold for USER GLOBALS that I need to change. It should be global however, since It's been declared in the config.dat and I've declared it as a E6POS type, I'm unsure if restarting the controller removes global variables.

(I've based the ,src module on the Actuator KRL code from your publication)

**UPDATE** Trying to stop the submit interpreter and trying again.

**Comment by markaren** [comment]
Two config.dat files sounds weird, perhaps it's causing the issue. I don't know. 
Mine looks like this (from the virtual office.Lite pad):

![image](https://cloud.githubusercontent.com/assets/6005031/11767196/047f78d4-a1a6-11e5-9b9e-894d46baa9a7.png)

With the user globals looking like:

![image](https://cloud.githubusercontent.com/assets/6005031/11767203/45165a8e-a1a6-11e5-8c26-b358f8a0b553.png)

From this, a program should be able to reference for instance the MYPOS variable the way you are doing it.

**Comment by CaptainMack** [comment]
Thank you @markaren,

Now the declaration of the variable problem has been solved, however trying to send a coodinate and afterwards moving it (in T1 mode), throws a:

    Software limit switch point cannot be reacher +A3

I guess it's something with my workspace setup, I'll see if I can fix it tonight.

**Comment by CaptainMack** [comment]
Thank you @markaren,

Now the declaration of the variable problem has been solved, however trying to send a coodinate and afterwards moving it (in T1 mode), throws a:

```
 Software limit switch point cannot be reacher +A3
```

or simply if i change the coordinates a bit:

```
Workspace error
```

I guess it's something with my workspace setup or maybe the MYPOS variable (it's auto filled to include A,B,C, S, T parameters). Or it might even be something related to the BASE/WORLD frame, if i have to define that within the code, I'll see if I can fix it tonight.

**Comment by markaren** [comment]
It has to do with the S and T parameters beeing zero.

You can solve it by copying the X, Y, and Z manually from the MYPOS into a locally declared POS variable. Or setting the S and T variables to something that works. Dunno what the default values are.

**Comment by CaptainMack** [comment]
It seems that it's solvable by reducing 

```
PTP_REL MYPOS C_PTP
```

to

```
PTP MYPOS
```

I've tried reducing the parameters to exclude S and T. However, switching to "pure" PTP has the consequence of making the movements quite jittery, i.e. moving to one point, stopping, moving to next (which PTP_REL + C_PTP is for) - but I guess the problem is that it only has one point in the beginning, thus there's no "sequence of movements". Or it maybe I need to set some approximation parameters ($APO) somewhere

**Comment by markaren** [comment]
Since you are in a loop the controller uses the same variable multiple times when making the continuous movement. While this doesn't sound very good, at least the controller thinks it has multiple points that it can create a motion from. I'm pretty confident that the problem is the  S and T values being bad. I've seen it before, and what I did was to copy the X, Y and Z values from MYPOS into a locally declared POS variable, which then has the default S and T values. Continuous movement did then work.

**Comment by CaptainMack** [comment]
Thank you once again @markaren, I was able to solve it and I'm using absolute coordinates at the moment (PTP with C_PTP). I've now controlled the robot with keyboard, mouse, leapmotion and now working on a markerbased path-generation tool, however when I try to read the current position of the robot using:

```
        //Read POS_ACT
        KRLReal act = KRLVariable.POS_ACT();
        client.readVariable(act);
        System.out.println(act);
```

I get the following error:

```
Exception in thread "main" java.lang.NumberFormatException: empty String
at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
at java.lang.Double.parseDouble(Unknown Source)
at no.hials.crosscom.KRL.KRLReal.setValueFromString(KRLReal.java:60)
at no.hials.crosscom.KRL.KRLVariable.update(KRLVariable.java:108)
at no.hials.crosscom.CrossComClient.readVariable(CrossComClient.java:257)
at no.hials.Test2.main(Test2.java:63)
```

i.e. where it reads the variable with **client.readVariable(act);**. It's able to read other variables, such as OV_JOG correctly.

**Comment by markaren** [comment]
Ah, yes.. That one only works when the robot is active (i.e running a program, or while pressing the grey switches down, if I remember correctly.

So just catch that error when it gets thrown, and during actuation it should read the values correctly.

**Comment by CaptainMack** [comment]
Setting a program with empty loop allowed me to read the variable.
In the KRLVariable class, the return type of the POS_ACT function was set to KRLReal, however KRLReal could not read the variable, as it was a E6Pos type that it tried to parse as a double. Changing the return type of POS_ACT() to KRLE6Pos made it work without throwing any exceptions.

Thanks!

**Comment by CaptainMack** [comment]
I've stumbled upon another problem, however, this is purely for informing you guys about it. When checking POS_ACT continuously, the id of the variable will increment until it reaches 255 (the limit of one byte) and next id will be 0 (and it expects 256), however the update function throws an error in this case

```
KRLVariable{id=255, name=$POS_ACT, value={A=-180.0, B=-9.93181E-13, C=-180.0, E1=0.0, E2=0.0, E3=0.0, E4=0.0, E5=0.0, E6=0.0, S=2.0, T=35.0, X=551.770081, Y=80.7867126, Z=30.0}, readTime=7ms}
Exception in thread "Thread-0" java.lang.RuntimeException: The returned id does not match the variable id! Should not happen...
    at no.hials.crosscom.KRL.KRLVariable.update(KRLVariable.java:108)
    at no.hials.crosscom.CrossComClient.readVariable(CrossComClient.java:257)
    at no.hials.TangibleBlockController.refresh(TangibleBlockController.java:119)
    at TUIO.TuioClient.acceptMessage(TuioClient.java:359)
    at com.illposed.osc.utility.OSCPacketDispatcher.dispatchMessage(OSCPacketDispatcher.java:73)
    at com.illposed.osc.utility.OSCPacketDispatcher.dispatchPacket(OSCPacketDispatcher.java:49)
    at com.illposed.osc.utility.OSCPacketDispatcher.dispatchBundle(OSCPacketDispatcher.java:56)
    at com.illposed.osc.utility.OSCPacketDispatcher.dispatchPacket(OSCPacketDispatcher.java:40)
    at com.illposed.osc.OSCPortIn.run(OSCPortIn.java:65)
   at java.lang.Thread.run(Unknown Source)
```

this: 256 id:0

and the update-function

```
public void update(int id, String strValue, long readTime) {
        if (this.id != id) {
            throw new RuntimeException("The returned id does not match the variable id! Should not happen...");
        }
        this.readTime = readTime;
        setValueFromString(strValue);
}
```
