### ISSUE TITLE
KUKAVARPROXY Sources

### ISSUE THREAD

**Issue by rlober** [aauc-mechlab/JOpenShowVar#4]
Hello,

I am working on a `c++` version of `JOpenShowVar` (to be added to github soon) and I am am currently having an issue with the `KUKAVARPROXY`. Basically I am sending requests with the proper byte format and `KUKAVARPROXY` is sending the responses with the correct format but the response `id` (i.e. the first 2 bytes) is always `0`. I want the code to be non-blocking, so the requests are sent from different threads and therefore I need a way to identify which response sent from `KUKAVARPROXY` corresponds to which request/thread. I was hoping that you guys could publish the sources for `KUKAVARPROXY` so I can debug this issue. I would of course be happy to contribute any improvements as well as the `c++` version of the `JOpenShowVar`.

For info, the `KUKAVARPROXY` is being run on a KR C4 compact. 

Thanks in advance!
Ryan

**Comment by markaren** [comment]
Hi, unfortunatly we do not have access to the KUKAVARPROXY source.
We got the binary source from the author of the C++ project OpenShowVar (https://sourceforge.net/projects/openshowvar/), from which I ported the send/receive protocol. 
 We asked for the source ourselves 1 or 2 years ago, unfortunately it could not be shared at that time. (Source belongs to some Itialian company)

**Comment by rlober** [comment]
@markaren 

Thanks for the info! Any idea if the company would be willing to share now? 

Just out of curiosity, when you send a message to `KUKAVARPROXY` do you get the response with the same ID? Could it be an issue with the `KUKAVARPROXY` I am using? It is not the one provided by your repo - actually I am not sure where it is from but my guess is the Source Forge repo.

Anyways, thanks for the help.

**Comment by markaren** [comment]
> Thanks for the info! Any idea if the company would be willing to share now?

Don't know

> do you get the response with the same ID

Yes, I do

**Comment by rlober** [comment]
Ok, I will try with your copy of `KUKAVARPROXY` and see if I get different results. 

Thanks again.

**Comment by filipposanfilippo** [comment]
Hi, I have recently discussed the possibility of sharing the source code. This may be possible now. I have forwarded you request to my colleague and I will let you know asap. Thank you for your interest in JOpenShowVar.

**Comment by rlober** [comment]
@filipposanfilippo 

Awesome! Thanks for asking about this - I hope the response is positive.

Just for visibility, I will re-open the issue until there is a definitive yes or no on this.

**Comment by filipposanfilippo** [comment]
I have got an answer and unfortunately, the source cannot be released yet.

I can suggest a possible solution to your issue. One way could be to create two different threads. Then you could divide between the two threads the message ID: for example from 1 to 100 thread 1, from 101 to 200 thread 2 ... so that you can distinguish the two threads.

Hope this helps you.

**Comment by rlober** [comment]
@filipposanfilippo 

Ok, thank you for asking in any case. I am first going to test with the version of the proxy provided in this repo and see if I get the message id in the response, if that doesn't work, then I will simply move non-blocking requests to their own threads with their own sockets. I don't know how many clients the proxy can handle at once but I will test and report the results here.

**Comment by sclcwwl** [comment]
Does sombody know how the KUKAVARPROXY works?

**Comment by simonschmeisser** [comment]
@filipposanfilippo Just out of curiosity, what hinders the release? NDA? code quality? Objections from Kuka? Do you have a time frame?

**Comment by ivareri** [comment]
Just a heads up, IMTS srl is in the process of releasing the source code for KUKAVARPROXY

https://www.imts.eu/open-sourcing-kukavarproxy/
https://github.com/ImtsSrl/KUKAVARPROXY

**Comment by rlober** [comment]
@ivareri 

Awesome news! I am looking forward to finally getting a peek at this mythical beast.

**Comment by djmeinicke** [comment]
Hello!
Could Everyone help me ?
Everyone use the CC++ aplication to communication whith a kuka
Has been a exemple for this?
