### ISSUE TITLE
bypassing the network

### ISSUE THREAD

**Issue by ghost** [aauc-mechlab/JOpenShowVar#8]
openShowVar is closed.

i am writing a direct interface for E6POS, but i think i can help you too.
This allows me to generate code for kuka manipulators directly.
Hence i dont need to use openShowVar.
But it means i still need to co-ordinate many kukas and so i need network comms.
I use a concurrent real time network to control things like the ROS and other similar libs.

But i dont know how easy it is to network with the kuka's and so maybe someone can let me know.

1. Is the kuka PAD the only way to talk to the kuka ?

**Comment by markaren** [comment]
Sorry for not answering sooner, but this is a more suitable question to ask in a KUKA/robotics forum
