### ISSUE TITLE
Runtime Error using KUKAVARPROXY

### ISSUE THREAD

**Issue by Fetzii** [aauc-mechlab/JOpenShowVar#9]
I started working with a KR C3 a few days ago and wanted to test the KUKAVARPROXY.
I copyed it to the Windows XP of the KR C3 started it and got this error: "Runtime Error 339":""Component 'CSWSK32.OCX' or one of its dependencies not correctly registered: a file is missing or invalid.".
After it failed I rebooted the System and the HMI isn't starting anymore.
I looked at the log but it wasn't helpful for me:

11/02/2017 10:59:03 Application Start
11/02/2017 11:00:46 ----  !!!GlobalExceptionHandler  -------------------
11/02/2017 11:00:46 Fail: System.Runtime.InteropServices.COMException (0x80080005): Starten des Servers fehlgeschlagen
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(Type objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(Type serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(Type serverType, Object[] props)
   at KUKARoboter.KRCModel.CrossKrc.KrcVariableCommands.get_AsyncVar()
   at KUKARoboter.KRCModel.CrossKrc.KrcVariableCommands.BeginShowVar(String variable, AsyncCallback callback, Object asyncState)
   at KUKARoboter.HMI.KukaHmiForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
11/02/2017 11:00:46 ----------------------------------------------------
11/02/2017 11:00:47 Error: Dispose Failed! Object reference not set to an instance of an object.
11/02/2017 11:00:47    at KUKARoboter.HMI.KukaHmiForm.Dispose(Boolean disposing)
11/02/2017 11:00:47 OnHandleDestroyed: OvProStatKey - KUKARoboter.AxMoveStatKeyLib.AxOvProStatKey
11/02/2017 11:00:47 OnHandleDestroyed: ParamStatKey0 - KUKARoboter.AxParaStatKeyLib.AxParaStatKey
11/02/2017 11:00:47 OnHandleDestroyed: ParamStatKey1 - KUKARoboter.AxParaStatKeyLib.AxParaStatKey
11/02/2017 11:00:47 OnHandleDestroyed: ParamStatKey2 - KUKARoboter.AxParaStatKeyLib.AxParaStatKey
11/02/2017 11:00:47 OnHandleDestroyed: ParamStatKey3 - KUKARoboter.AxParaStatKeyLib.AxParaStatKey
11/02/2017 11:00:47 OnHandleDestroyed: ParamStatKey4 - KUKARoboter.AxParaStatKeyLib.AxParaStatKey
11/02/2017 11:00:47 OnHandleDestroyed: MoveStatKey0 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: MoveStatKey1 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: MoveStatKey2 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: MoveStatKey3 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: MoveStatKey4 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: MoveStatKey5 - KUKARoboter.AxMoveStatKeyLib.AxMoveStatKey
11/02/2017 11:00:48 OnHandleDestroyed: EAxisStatkey - KUKARoboter.AxMoveStatKeyLib.AxEAxisStatKey
11/02/2017 11:00:48 OnHandleDestroyed: IncStatKey - KUKARoboter.AxMoveStatKeyLib.AxIncStatKey
11/02/2017 11:00:48 OnHandleDestroyed: CoordStatKey - KUKARoboter.AxMoveStatKeyLib.AxCoordStatKey
11/02/2017 11:00:48 OnHandleDestroyed: OvJogStatKey - KUKARoboter.AxMoveStatKeyLib.AxOvJogStatKey
11/02/2017 11:00:48 OnHandleDestroyed: DomStatKey - KUKARoboter.AxMoveStatKeyLib.AxDomStatKey
11/02/2017 11:00:48 OnHandleDestroyed:  - KUKARoboter.AxNewUserKeyBar.AxNewUserKeyBar
11/02/2017 11:00:48 OnHandleDestroyed: ModeStatKey - KUKARoboter.AxMoveStatKeyLib.AxModeStatKey
11/02/2017 11:00:48 OnHandleDestroyed: StepStatKey - KUKARoboter.AxMoveStatKeyLib.AxStepStatKey
11/02/2017 11:00:48 Error: Dispose Failed! Object reference not set to an instance of an object.
11/02/2017 11:00:48    at KUKARoboter.HMI.KukaHmiForm.Dispose(Boolean disposing)
11/02/2017 11:00:48 HMI: Application End

I can't find a solution to my problem. I hope you can help me out!

**Comment by markaren** [comment]
Sorry to hear about your problem.
Unfortunately, as KUKAVARPROXY is 3rd party and closed source software (originates from https://sourceforge.net/projects/openshowvar/), there is not much I can help you with.

**Comment by Fetzii** [comment]
Any tips that I could try?

**Comment by ghost** [comment]
Wrong account..

**Comment by markaren** [comment]
Not other than restoring from a backup if you have one. I myself have not worked with KUKA robots in years, and have zero familiarity with the KRC3 family.

**Comment by Fetzii** [comment]
I have a backup CD of the software for the KRC3, but it contains only the folders and not the installtion files. If the KUKAVARPROXY.exe changed anything in the registry it won't help i quess.
I'm not sure if it will get worse when I just copy the files from the backup CD and overwrite the current files.

**Comment by markaren** [comment]
I would really consult with someone that has more experience with KRC3 software and KUKA robotics in general. I am really not to much help here.

**Comment by Fetzii** [comment]
Ok, do you know someone who could help me out?

Thanks for your help

**Comment by markaren** [comment]
Is KUKA support an option?

http://www.robot-forum.com/robotforum/kuka-robot-forum/ could be an option, but it seems down. Don't know for how long..

Btw, here is a long shot: Did you copy all the contents from KUKAVARPROXY over to the robot. That the .exe and the two other files. If not I would try to rerun the application with all the files present? But it is a long shot. I do not what KUKAVARPROXY does or how it works.

**Comment by Fetzii** [comment]
Yeah, I used all the files. Why I get the runtime error I don't know, either. I could try other versions of the KUKAVARPROXY. 
I wrote to nowire, who developed openshowvar and M.Fago, who is/was an employee at IMTS S.r.L. Company. They developed the KUKAVARPROXY if I'm not mistaken.
I hope they can give me some information.

Yeah they are down for a whole day now. The German counterpart is down, too. Hope they will be back online soon.
 
I wrote a mail to KUKA. They haven't answered it yet. If they don't answer it I'll call them.

**Comment by Fetzii** [comment]
I have another question.
Can you start the KUKAVARPROXY on any other Windows device? It won't work properly but can you start it?
When I start it on my PC it shows the same runtime error.

**Comment by markaren** [comment]
I cannot answer anything related to KUKAVARPROXY, sorry.

**Comment by Fetzii** [comment]
I was able to contact Mr. Fago.

If the information is useful for anyone:
There is no correlation between KUKAVARPROXY and KUKA System HMI.

Thx, for your help and your time!
